
version: '3'


services:
    web:
      restart: always
      build:
        context: .
      ports:
       - '8000:8000'
      depends_on:
       - db
      volumes:
       - .:/src
      networks:
       - main

    db:
      image: postgres
      networks:
        - main

networks:
  main: