version: '3'


services:
    web:
      build: .
      ports:
       - '8000:8000'
      depends_on:
       - db
      volumes:
       - .:/src

    db:
      image: postgres
      volumes:
        - /var/lib/postgresql/data
      expose:
        - 5432