
version: '2'


services:
    web:
      restart: always
      build:
        context: .
      command: >
        bash -c "python3 manage.py migrate
        && python3 manage.py runserver 0.0.0.0:8000"
      ports:
       - '8000:8000'
      depends_on:
       - db
      volumes:
       - .:/src
      networks:
       - main

    db:
      image: postgres
      networks:
        - main

networks:
  main: