version: '3'


services:
    web:
      build: .
      ports:
       - '8000:8000'
      depends_on:
       - db
      env_file:
        - .djangoenv.dev
      volumes:
       - .:/src

    db:
      image: "postgres:11-alpine"
      env_file:
        - .djangoenv.dev
      expose:
        - 5432
      volumes:
        - pgdata:/var/lib/postgresql/11/data
volumes:
  pgdata:
