version: '3'


services:
    web:
      build: .
      restart: always
      command: >
        bash -c "python3 manage.py migrate
        && python3 manage.py runserver 0.0.0.0:8000"
      ports:
       - '8000:8000'
      depends_on:
       - db
      volumes:
       - .:/src

    db:
      image: postgres
      expose:
        - 5432