version: '3'

services:
  web:
    build:
      dockerfile: deployment/Dockerfile.prod
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: "postgres:11-alpine"
    volumes:
      - /pgdata:/var/lib/postgresql/10/data

  nginx:
    build:
      dockerfile: deployment/nginx/Dockerfile
      context: .
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  pgdata: