# Generated by Django 2.2.2 on 2019-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages_count',
            field=models.IntegerField(default=0),
        ),
    ]
