# Generated by Django 2.2.2 on 2019-06-26 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190626_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_add',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 9, 17, 9, 270167)),
        ),
    ]
