# Generated by Django 2.2.2 on 2019-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190626_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
