# Generated by Django 2.2.2 on 2019-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190626_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
